# Generated by Django 4.1 on 2023-02-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_song_songlnk'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_art',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
