# Generated by Django 4.1 on 2023-02-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_song_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='desc',
            field=models.CharField(default='FART BUTT POOP', max_length=360),
        ),
    ]
