# Generated by Django 4.1 on 2023-02-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_song_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlnk',
            name='icon',
            field=models.CharField(default='fail', max_length=32),
            preserve_default=False,
        ),
    ]
