# Generated by Django 4.1 on 2023-02-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_songlnk_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(default='ERROR', max_length=32),
        ),
    ]
