# Generated by Django 4.1 on 2023-04-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_location_city_location_region_alter_location_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
