# Generated by Django 4.1 on 2023-04-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnklog',
            name='lnk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lnk'),
        ),
    ]
