# Generated by Django 4.1 on 2023-04-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_lnklog_lnk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover_art',
        ),
        migrations.RemoveField(
            model_name='song',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
        migrations.AddField(
            model_name='song',
            name='redirect_url',
            field=models.URLField(default='https://jxsen.com/'),
        ),
    ]
