# Generated by Django 4.1 on 2023-05-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_song_cover_art_remove_song_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnklog',
            name='lnk',
        ),
        migrations.RemoveField(
            model_name='lnklog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='songlnk',
            name='song',
        ),
        migrations.DeleteModel(
            name='Lnk',
        ),
        migrations.DeleteModel(
            name='LnkLog',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='SongLnk',
        ),
    ]
